#----- General Settings -----#
title: TeamExyKings
email: teamexykings@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Output options (more information on Jekyll's site)
timezone: "Asia/Kolkata"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 4

kramdown:
  input: GFM


# Custom Directories
include: ['devices']

# Default YAML values (more information on Jekyll's site)
author-name: Griffin98

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.jpg"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#16131F"
navbar-text-col: "#FFFFFF"
navbar-children-col: "#16131F"
page-col: "#000000"
text-light: "#FFFFFF"
text-dark: "#000000"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#16131F"
footer-text-col: "#FFFFFF"
footer-link-col: "#404040"

announcement:
  - "LightRom For S8/S8+ has been updated to August Base"
  - "LightRom For S9/S9+ has been updated to August Base"
  - "LightRom For S10/S10+ has been updated to August Base"


plugins:
  - jekyll-paginate
  - jekyll-sitemap
